# Generated by Django 5.1.6 on 2025-04-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateflix_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
